name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Set up directories
        run: |
          mkdir -p data/haystack_store
          mkdir -p flask_session
          mkdir -p logs
          
      - name: Create README files to maintain directory structure
        run: |
          echo "# Haystack Store Directory\nThis directory is used for storing Haystack memory persistence files." > data/haystack_store/README.md
          echo "# Flask Session Directory\nThis directory is used for storing Flask session files." > flask_session/README.md
          echo "# Log Files Directory\nThis directory contains log files generated by the application." > logs/README.md

      - name: Run pytest tests
        run: |
          python -m pytest tests/ -v --exclude-file="test_api.py"
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TESTING: "true"

  deploy:
    name: Deploy to Railway
    needs: test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Verify deployment
        run: |
          echo "Deployment to Railway completed successfully"
          echo "Application should now be available at your Railway domain"
          
      - name: Set deployment status
        run: echo "DEPLOY_STATUS=success" >> $GITHUB_ENV
        
    outputs:
      deploy_status: ${{ env.DEPLOY_STATUS }}
        
  notify:
    name: Notify deployment status
    needs: [test, deploy]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check deployment status
        run: |
          if [[ "${{ needs.deploy.outputs.deploy_status }}" == "success" ]]; then
            echo "## ✅ Deployment Successful" >> $GITHUB_STEP_SUMMARY
            echo "The application has been successfully deployed to Railway." >> $GITHUB_STEP_SUMMARY
          else
            echo "## ❌ Deployment Failed" >> $GITHUB_STEP_SUMMARY
            echo "The deployment to Railway failed. Please check the logs for more information." >> $GITHUB_STEP_SUMMARY
          fi 