name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up directories
        run: |
          mkdir -p data/haystack_store
          mkdir -p flask_session
          mkdir -p logs
          
      - name: Create README files to maintain directory structure
        run: |
          echo "# Haystack Store Directory\nThis directory is used for storing Haystack memory persistence files." > data/haystack_store/README.md
          echo "# Flask Session Directory\nThis directory is used for storing Flask session files." > flask_session/README.md
          echo "# Log Files Directory\nThis directory contains log files generated by the application." > logs/README.md

      - name: Run tests
        run: |
          python -m tests.test_api
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      
      - name: Install Railway CLI
        run: npm install -g @railway/cli
        
      - name: Deploy to Railway
        if: success()
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 